version: '3.8'

services:
  # 1. Nossa Landing Zone (Banco de Dados Relacional)
  postgres_landing:
    image: postgres:15
    container_name: postgres_landing_zone
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: radar_sp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_dados

  # 2. Orquestrador (Apache Airflow)
  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow_orquestrador
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False # Desativa DAGs de exemplo para limpar a interface
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    command: standalone
    networks:
      - rede_dados
    depends_on:
      - postgres_landing

  #3.Objeto de armazenamento (minIO/S3)
  mi nio-datalake:
    image: minio/minio
    container_name: minio-datalake
    ports:
      - "9000:9000" # Porta da API (S3)
      - "9001:9001" # Porta da Interface Web (Console)
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  #.Objeto de Procesamento de dados
  pyspark_workspace:
    image: jupyter/pyspark-notebook:spark-3.4.1
    container_name: pyspark_workspace
    ports:
      - "8888:8888" # Interface do Jupyter Lab
      - "4040:4040" # Spark UI (para monitorar o processamento de dados)
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./notebooks:/home/jovyan/work

# Declaração dos volumes e redes que usamos acima
volumes:
  postgres_data:
  minio_data:
networks:
  rede_dados:
    driver: bridge